USE [TinhTienDien]
GO

--Tao khoa chinh
--Person_info
ALTER TABLE [dbo].[PERSON_INFO]
ADD CONSTRAINT [PK_PERSON_INFO_CCCD] PRIMARY KEY ([CCCD])

--Account
ALTER TABLE [dbo].[ACCOUNT]
ADD CONSTRAINT [PK_ACCOUNT_CCCD] PRIMARY KEY ([CCCD])

--E_METER
ALTER TABLE [dbo].[E_METER]
ADD CONSTRAINT [PK_E_METER_ID] PRIMARY KEY ([ID_E_METER])

--Tao khoa phu
--Table Account
ALTER TABLE [dbo].[ACCOUNT]
ADD CONSTRAINT [FK_ACCOUNT_CCCD__PERSON_INFO_CCCD] FOREIGN KEY ([CCCD]) REFERENCES [dbo].[PERSON_INFO]([CCCD])
ON UPDATE CASCADE 

--Table Chuho
ALTER TABLE [dbo].[CHUHO]
ADD CONSTRAINT [FK_CHUHO_CCCD__ACCOUNT_CCCD] FOREIGN KEY ([CCCD]) REFERENCES [dbo].[ACCOUNT]([CCCD])
ON UPDATE CASCADE 

ALTER TABLE [dbo].[CHUHO]
ADD CONSTRAINT [FK_CHUHO_CCCD__STAFFS_CCCD] FOREIGN KEY ([ID_Staff]) REFERENCES [dbo].[STAFFS]([ID_Staffs])

--Table Staffs
ALTER TABLE [dbo].[STAFFS]
ADD CONSTRAINT [FK_STAFFS_CCCD__ACCOUNT_CCCD] FOREIGN KEY ([CCCD]) REFERENCES [dbo].[ACCOUNT]([CCCD])
ON UPDATE CASCADE 

--Table E_Meter
ALTER TABLE [dbo].[E_METER]
ADD CONSTRAINT [FK_E_METER_CCCD__CHUHO_ID] FOREIGN KEY ([ID_Chuho]) REFERENCES [dbo].[CHUHO]([ID_Chuho])

--Table Invoices
ALTER TABLE [dbo].[INVOICES]
ADD CONSTRAINT [FK_INVOICES_ID_Staff__STAFFS_ID] FOREIGN KEY ([ID_Staff]) REFERENCES [dbo].[STAFFS]([ID_Staffs])

ALTER TABLE [dbo].[INVOICES]
ADD CONSTRAINT [FK_INVOICES_ID_E_Meter__E_METER_ID] FOREIGN KEY ([Id_E_Meter]) REFERENCES [dbo].[E_METER]([ID_E_METER])

ALTER TABLE [dbo].[INVOICES]
ADD CONSTRAINT [FK_INVOICES_ID_Chuho__CHUHO_ID] FOREIGN KEY ([ID_Chuho]) REFERENCES [dbo].[CHUHO]([ID_Chuho])