USE [TinhTienDien]
GO

--Personal_info
ALTER TABLE [dbo].[PERSON_INFO]
ADD CONSTRAINT PERSON_INFO_Check_CCCD
CHECK (LEN([CCCD]) = 12 AND [CCCD] NOT LIKE '%[^0-9]%')

ALTER TABLE [dbo].[PERSON_INFO]
ADD CONSTRAINT PERSON_INFO_Check_Phone
CHECK (LEN([Phone]) = 10 AND [Phone] NOT LIKE '%[^0-9]%')

--Account
ALTER TABLE [dbo].[ACCOUNT]
ADD CONSTRAINT ACCOUNT_Check_CCCD
CHECK (LEN([CCCD]) = 12 AND [CCCD] NOT LIKE '%[^0-9]%')

ALTER TABLE [dbo].[ACCOUNT]
ADD CONSTRAINT ACCOUNT_Check_Privilege
CHECK ([Privilege] >= 0 AND [Privilege] <= 2)

--Chu ho
ALTER TABLE [dbo].[CHUHO]
ADD CONSTRAINT CHUHO_Check_CCCD
CHECK (LEN([CCCD]) = 12 AND [CCCD] NOT LIKE '%[^0-9]%')

--Staffs
ALTER TABLE [dbo].[STAFFS]
ADD CONSTRAINT STAFFS_Check_CCCD
CHECK (LEN([CCCD]) = 12 AND [CCCD] NOT LIKE '%[^0-9]%')

--E_METER
ALTER TABLE [dbo].[E_METER]
ADD CONSTRAINT E_METER_Check_ID
CHECK (LEN([ID_E_METER]) <=8 AND [ID_E_METER] NOT LIKE '%[^0-9]%')

--INVOICES
ALTER TABLE [dbo].[INVOICES]
ADD CONSTRAINT INVOICES_Check_Start_End_Num
CHECK ([Start_Num] >= 0 AND [End_Num] > [Start_Num])

ALTER TABLE [dbo].[INVOICES]
ADD CONSTRAINT INVOICES_Check_E_METER_ID
CHECK (LEN([Id_E_Meter]) <=8 AND [Id_E_Meter] NOT LIKE '%[^0-9]%')